name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: curl, dom, fileinfo, json, simplexml, xmlwriter, zip
          tools: composer:v2

      - name: Determine composer cache directory
        id: composer-cache
        run: echo "directory=$(composer config cache-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.directory }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('composer.json', 'composer.lock') }}
          restore-keys: ${{ matrix.php }}-composer-

      - name: Validate composer configuration
        run: composer validate --strict

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --prefer-stable
          composer dump-autoload -o

      - name: Audit dependencies
        run: composer audit

      - name: Run tests
        env:
          XDEBUG_MODE: coverage
        run: |
          mkdir -p build/logs
          php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=build/logs/clover.xml

      - name: Run phpstan
        run: |
          php vendor/bin/phpstan analyse

      - name: Upload coverage results to Coveralls
        if: ${{ matrix.php == '7.4' }}
        env:
            COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            composer global require php-coveralls/php-coveralls
            php-coveralls --coverage_clover=build/logs/clover.xml -v

      - name: Upload coverage results to Codecov
        if: ${{ matrix.php == '7.4' }}
        uses: codecov/codecov-action@v5
        with:
          files: build/logs/clover.xml

      - name: Archive logs artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: logs_php-${{ matrix.php }}
          path: |
            build/logs
          if-no-files-found: ignore
